In [26]:
import torch
import tensorflow as tf


def pr(*sth):
    print(sth)

## Scalars

In [27]:
x1 = torch.tensor(3)
x2 = torch.tensor([3])

In [28]:
pr(x1, x2)

(tensor(3), tensor([3]))


In [29]:
pr(x1.shape, x2.shape)

(torch.Size([]), torch.Size([1]))


In [30]:
x1 + x2, x1 * x2, x1**x2

(tensor([6]), tensor([9]), tensor([27]))

In [31]:
x1 = tf.constant(3)
x2 = tf.constant([4])

In [32]:
x1 + x2, x1 - x2, x1 * x2

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([7])>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([-1])>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([12])>)

## Vectors

A vector is simply a list of scalar values. We call these values the elements(entries or components) of the vector. 

In [33]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [34]:
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

### Length, Dimensionality, Shape 

In [35]:
x = torch.arange(4,10)
len(x), x.shape

(6, torch.Size([6]))

In [36]:
x = tf.range(4,10)
len(x), tf.shape(x), x.shape

(6, <tf.Tensor: shape=(1,), dtype=int32, numpy=array([6])>, TensorShape([6]))

## Matrices

In [37]:
A = torch.arange(25).reshape((-1,5))
A.T

tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])

In [38]:
A = tf.reshape(tf.range(36),(-1,6))
tf.transpose(A) # speechless 

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])>

## Tensors

In [39]:
X = torch.arange(20).reshape(2,2,5)
X

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]])

In [40]:
X = tf.reshape(tf.range(24), (2,3,4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

## Reduction